### ISSUE TITLE
Readme Assumes 'alan' in path for tasks.json, the default template doesn't 

### ISSUE THREAD

**Issue by LeonHagenaarsKeus** [M-industries/AlanForVSCode#1]
The following part:
`"command": "bash -c 'pushd ${fileDirname} && alan validate vscode --wire && popd'" `
Only works if this alan is in your path.

When using https://github.com/M-industries/AlanProjectTemplate, this does not work.

`"command": "bash -c 'pushd ${fileDirname} && ${workspaceRoot}/alan validate vscode --wire && popd'" `
Works like a charm

**Comment by braver** [comment]
Alan is now assumed to be available in the workspaceRoot
